[package]
cairo-version = "2.4.0"
name = "risingrevenant"
version = "0.3.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.5.0" }
origami = { git = "https://github.com/dojoengine/origami.git" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "a8edfb80987c9b2e758e5e4d6763b8f8789d3e94" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]

# local
rpc_url = "http://localhost:5050"
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
#world_address = ""

# slot
#rpc_url = "https://api.cartridge.gg/x/rr-demo/katana"
#account_address = "0x247015d55088758b0712bc62351d864f5efdc6a128213708dc9ad92486ff1c2"
#private_key = "0x44bcb4a4e4fccd06da386dd7a99a00a091d337240cf7d1d9946ca9625b9e816"
#world_address = ""


[tool.fmt]
sort-module-level-items = true
