[package]
cairo-version = "2.2.0"
name = "realmsrisingrevenant"
version = "0.2.3"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.3.15" }
origami = { git = "https://github.com/dojoengine/origami.git", rev = "eb52cb6c4cc3ab86fa695606d269bc9143ae8a29" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "a8edfb80987c9b2e758e5e4d6763b8f8789d3e94" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/rr-demo/katana"
# rpc_url = "http://localhost:5050"
# Default account for katana with seed = 0
# account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
# private_key = "0x1800000000300000180000000000030000000000003006001800006600"

account_address = "0x6d1e2e7566fea34a48a25413f87949b24527ca4719571268a6c3443585725e"
private_key = "0x553d2cccd54534b9f2830c7dc2113ebe96e8c3f98b244cefca4a20c1a175522"

world_address = "0x6232fe23b5b1504525ab921d824fd1ec130d0ab6efc7cae92f2afab94758a3e"
# keystore_password = "password"
# keystore_path = "../keystore.json"

[tool.fmt]
sort-module-level-items = true
